$ANSIBLE_VAULT;1.1;AES256
61343763343034356564623136373131323534623433633034613463333139353433366361646464
3432303939623731643831633135626336383662613738380a393738613961323634333736616135
62373238623661666632636331303166643535373866316164626433616332663430306136626265
3930623630646165380a393764333235666166653064663237313133323738336461636338666430
61613865343436663434326664396565396539353365333630643738393763646533393437343738
34343834343938313766376637323061303035396538366539393261613539366532343161666663
643230626164323830313530643736613236
